[2023-06-21T02:08:50.755+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-21T02:08:50.317335+00:00 [queued]>
[2023-06-21T02:08:50.760+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-21T02:08:50.317335+00:00 [queued]>
[2023-06-21T02:08:50.760+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-21T02:08:50.768+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-21 02:08:50.317335+00:00
[2023-06-21T02:08:50.771+0000] {standard_task_runner.py:57} INFO - Started process 258 to run task
[2023-06-21T02:08:50.774+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'oracle_connection_test_dag', 'execute_function_task', 'manual__2023-06-21T02:08:50.317335+00:00', '--job-id', '429', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/OracleTest_Dag.py', '--cfg-path', '/tmp/tmptxh48in8']
[2023-06-21T02:08:50.775+0000] {standard_task_runner.py:85} INFO - Job 429: Subtask execute_function_task
[2023-06-21T02:08:50.801+0000] {task_command.py:410} INFO - Running <TaskInstance: oracle_connection_test_dag.execute_function_task manual__2023-06-21T02:08:50.317335+00:00 [running]> on host 68331b7f6fd1
[2023-06-21T02:08:50.840+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='oracle_connection_test_dag' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-21T02:08:50.317335+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-21T02:08:50.317335+00:00'
[2023-06-21T02:08:50.841+0000] {logging_mixin.py:149} INFO - Creating Oracle Testing Class
[2023-06-21T02:08:50.841+0000] {logging_mixin.py:149} INFO - Attempting to connect to oracle
[2023-06-21T02:08:50.841+0000] {logging_mixin.py:149} INFO - Current User: ***
[2023-06-21T02:08:51.279+0000] {warnings.py:109} WARNING - /opt/***/dags/Python-Delta-Lake/OracleTest/OracleDbTest.py:20: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_ora = pd.read_sql(query, con=oracle_connection)

[2023-06-21T02:08:53.654+0000] {logging_mixin.py:149} INFO - (1, 1)
[2023-06-21T02:08:53.684+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-21T02:08:53.788+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=oracle_connection_test_dag, task_id=execute_function_task, execution_date=20230621T020850, start_date=20230621T020850, end_date=20230621T020853
[2023-06-21T02:08:53.836+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-21T02:08:53.844+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
