[2023-06-29T21:00:01.024+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task scheduled__2023-06-29T20:00:00+00:00 [queued]>
[2023-06-29T21:00:01.028+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Oracle_to_Filestore.execute_function_task scheduled__2023-06-29T20:00:00+00:00 [queued]>
[2023-06-29T21:00:01.029+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-29T21:00:01.035+0000] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): execute_function_task> on 2023-06-29 20:00:00+00:00
[2023-06-29T21:00:01.038+0000] {standard_task_runner.py:57} INFO - Started process 252 to run task
[2023-06-29T21:00:01.040+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Oracle_to_Filestore', 'execute_function_task', 'scheduled__2023-06-29T20:00:00+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/Python-Delta-Lake/Dags/SparkOracle2FileStoreDag.py', '--cfg-path', '/tmp/tmpiklptpeg']
[2023-06-29T21:00:01.042+0000] {standard_task_runner.py:85} INFO - Job 578: Subtask execute_function_task
[2023-06-29T21:00:01.067+0000] {task_command.py:410} INFO - Running <TaskInstance: Oracle_to_Filestore.execute_function_task scheduled__2023-06-29T20:00:00+00:00 [running]> on host 3300c969268f
[2023-06-29T21:00:01.107+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='phomsophaN@saccounty.net' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Oracle_to_Filestore' AIRFLOW_CTX_TASK_ID='execute_function_task' AIRFLOW_CTX_EXECUTION_DATE='2023-06-29T20:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-06-29T20:00:00+00:00'
[2023-06-29T21:00:01.108+0000] {logging_mixin.py:149} INFO - SparkSession Not found, creating one
[2023-06-29T21:00:01.108+0000] {logging_mixin.py:149} INFO - setting up configured spark connection Cluster
[2023-06-29T21:00:01.108+0000] {logging_mixin.py:149} INFO - Initializing support for delta lake spark context
[2023-06-29T21:00:03.197+0000] {logging_mixin.py:149} INFO - Returning Spark Context
[2023-06-29T21:00:03.198+0000] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:50070')>.
[2023-06-29T21:00:03.198+0000] {client.py:1123} INFO - Listing '/'.
[2023-06-29T21:00:03.200+0000] {logging_mixin.py:149} INFO - Cannot Establish HDFS connection: HTTPConnectionPool(host='localhost', port=50070): Max retries exceeded with url: /webhdfs/v1/?user.name=root&op=LISTSTATUS (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6dbb297e20>: Failed to establish a new connection: [Errno 111] Connection refused'))
[2023-06-29T21:00:03.200+0000] {logging_mixin.py:149} INFO - HDFS Not Connected
[2023-06-29T21:00:03.201+0000] {logging_mixin.py:149} INFO - Attempt to read Msql Table by query: select * from DeltaLake.OracleTablesLog
        where OracleRows < 1000000 AND OracleRows > 10000 AND OracleSizeInMB < 4000 AND CountyFilter IS NOT NULL and PrimaryKeyColumn !=''
[2023-06-29T21:00:03.201+0000] {logging_mixin.py:149} INFO - Read on Mssql table failed: 'NoneType' object has no attribute 'read'
[2023-06-29T21:00:03.201+0000] {logging_mixin.py:149} INFO - Error Running Pipeline:'NoneType' object has no attribute 'toPandas'
[2023-06-29T21:00:03.201+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-29T21:00:03.207+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=Oracle_to_Filestore, task_id=execute_function_task, execution_date=20230629T200000, start_date=20230629T210001, end_date=20230629T210003
[2023-06-29T21:00:03.258+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-29T21:00:03.269+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
